/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as SignSignTokenRouteImport } from './routes/sign.$signToken'
import { Route as VaultIndexRouteImport } from './routes/vault.index'
import { Route as VaultFolderIdRouteImport } from './routes/vault.$folderId'
import { Route as VerifyDocumentHashRouteImport } from './routes/verify.$documentHash'
import { Route as InvitationsTokenAcceptRouteImport } from './routes/invitations.$token.accept'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignSignTokenRoute = SignSignTokenRouteImport.update({
  id: '/sign/$signToken',
  path: '/sign/$signToken',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultFolderIdRoute = VaultFolderIdRouteImport.update({
  id: '/vault/$folderId',
  path: '/vault/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyDocumentHashRoute = VerifyDocumentHashRouteImport.update({
  id: '/verify/$documentHash',
  path: '/verify/$documentHash',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenAcceptRoute = InvitationsTokenAcceptRouteImport.update({
  id: '/invitations/$token/accept',
  path: '/invitations/$token/accept',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lifecycle': typeof LifecycleRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/trash': typeof TrashRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/sign/$signToken': typeof SignSignTokenRoute
  '/vault/$folderId': typeof VaultFolderIdRoute
  '/verify/$documentHash': typeof VerifyDocumentHashRoute
  '/vault/': typeof VaultIndexRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lifecycle': typeof LifecycleRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/trash': typeof TrashRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/sign/$signToken': typeof SignSignTokenRoute
  '/vault/$folderId': typeof VaultFolderIdRoute
  '/verify/$documentHash': typeof VerifyDocumentHashRoute
  '/vault': typeof VaultIndexRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lifecycle': typeof LifecycleRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/trash': typeof TrashRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/sign/$signToken': typeof SignSignTokenRoute
  '/vault/$folderId': typeof VaultFolderIdRoute
  '/verify/$documentHash': typeof VerifyDocumentHashRoute
  '/vault/': typeof VaultIndexRoute
  '/invitations/$token/accept': typeof InvitationsTokenAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/billing'
    | '/forgot-password'
    | '/lifecycle'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/team'
    | '/trash'
    | '/documents/$documentId'
    | '/shared/$token'
    | '/sign/$signToken'
    | '/vault/$folderId'
    | '/verify/$documentHash'
    | '/vault/'
    | '/invitations/$token/accept'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/billing'
    | '/forgot-password'
    | '/lifecycle'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/team'
    | '/trash'
    | '/documents/$documentId'
    | '/shared/$token'
    | '/sign/$signToken'
    | '/vault/$folderId'
    | '/verify/$documentHash'
    | '/vault'
    | '/invitations/$token/accept'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/billing'
    | '/forgot-password'
    | '/lifecycle'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/team'
    | '/trash'
    | '/documents/$documentId'
    | '/shared/$token'
    | '/sign/$signToken'
    | '/vault/$folderId'
    | '/verify/$documentHash'
    | '/vault/'
    | '/invitations/$token/accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BillingRoute: typeof BillingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LifecycleRoute: typeof LifecycleRoute
  LoginRoute: typeof LoginRoute
  MfaRoute: typeof MfaRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  TrashRoute: typeof TrashRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  SharedTokenRoute: typeof SharedTokenRoute
  SignSignTokenRoute: typeof SignSignTokenRoute
  VaultFolderIdRoute: typeof VaultFolderIdRoute
  VerifyDocumentHashRoute: typeof VerifyDocumentHashRoute
  VaultIndexRoute: typeof VaultIndexRoute
  InvitationsTokenAcceptRoute: typeof InvitationsTokenAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$signToken': {
      id: '/sign/$signToken'
      path: '/sign/$signToken'
      fullPath: '/sign/$signToken'
      preLoaderRoute: typeof SignSignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$folderId': {
      id: '/vault/$folderId'
      path: '/vault/$folderId'
      fullPath: '/vault/$folderId'
      preLoaderRoute: typeof VaultFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$documentHash': {
      id: '/verify/$documentHash'
      path: '/verify/$documentHash'
      fullPath: '/verify/$documentHash'
      preLoaderRoute: typeof VerifyDocumentHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token/accept': {
      id: '/invitations/$token/accept'
      path: '/invitations/$token/accept'
      fullPath: '/invitations/$token/accept'
      preLoaderRoute: typeof InvitationsTokenAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BillingRoute: BillingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LifecycleRoute: LifecycleRoute,
  LoginRoute: LoginRoute,
  MfaRoute: MfaRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  TrashRoute: TrashRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  SharedTokenRoute: SharedTokenRoute,
  SignSignTokenRoute: SignSignTokenRoute,
  VaultFolderIdRoute: VaultFolderIdRoute,
  VerifyDocumentHashRoute: VerifyDocumentHashRoute,
  VaultIndexRoute: VaultIndexRoute,
  InvitationsTokenAcceptRoute: InvitationsTokenAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
